### ISSUE TITLE
Change website of RS5

### ISSUE THREAD

**Issue by ediordna** [FixMyBerlin/rsv-dossier#110]
Consider changing the website here:
https://github.com/FixMyBerlin/rsv-dossier/blob/42727938ccd9684f2f3fc566018c227529cf3480/src/radschnellwege/meta/meta.json#L105C21-L105C21

to: https://www.rems-murr-kreis.de/bauen-umwelt-und-verkehr/radwege/radschnellwege/rs5-schorndorf-fellbach

**Comment by tordans** [comment]
@ediordna die Änderung ist live https://main--rsv-dossier.netlify.app/steckbriefe/rs5-baden-wuerttemberg — Danke für den Hinweis
